# Generated by Django 5.2.3 on 2025-08-13 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='assigned_installer',
            field=models.ForeignKey(blank=True, help_text='The CustomUser id to bind directly for notifications.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_installations_directly', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installation',
            name='assignment_expires_at',
            field=models.DateTimeField(blank=True, help_text="Crucial Field. Timestamp for when the installer's offer to accept expires. Null if not pending.", null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='charger_model',
            field=models.ForeignKey(help_text='The charger model to be installed.', on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='accounts.chargermodel'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='customer',
            field=models.ForeignKey(help_text='The customer associated with this installation.', on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='installation_created_date',
            field=models.DateField(blank=True, help_text='The date when the installation job was originally created.', null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='installation_id',
            field=models.CharField(editable=False, help_text='Unique identifier for the installation job.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='installer',
            field=models.ForeignKey(blank=True, help_text='The installer assigned to this job. Can be null if unassigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_installations', to='accounts.installerprofile'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional notes or comments for the installation.', null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PENDING_ACCEPTANCE', 'Pending Acceptance'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='SUBMITTED', help_text='The current status of the installation job.', max_length=20),
        ),
        migrations.AlterField(
            model_name='installation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last update to the record.'),
        ),
        migrations.AlterField(
            model_name='installerprofile',
            name='user',
            field=models.OneToOneField(blank=True, help_text='The CustomUser account associated with this installerprofile.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
