# Generated by Django 5.2.3 on 2025-08-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installerprofile',
            name='operational_state',
            field=models.CharField(blank=True, choices=[('Central 1', 'Wilayah Persekutuan KL, Putrajaya'), ('Central 2', 'Selangor'), ('Northern', 'Perak, Kedah, Perlis, Penang'), ('Southern', 'N.Sembilan, Melaka, Johor'), ('East Coast', 'Pahang, Terengganu, Kelantan'), ('East Malaysia', 'Sabah, Sarawak')], max_length=50, null=True),
        ),
    ]
