# Generated by Django 5.2.3 on 2025-08-13 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_installation_assigned_installer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text="The content of the notification message (e.g., 'Installer John Doe has accepted the job.').")),
                ('is_read', models.BooleanField(default=False, help_text='Tracks if the user has viewed this notification. Defaults to False.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the notification was created.')),
                ('related_installation', models.ForeignKey(blank=True, help_text='An optional link to the relevant installation, allowing clicks to navigate directly to the job details.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='accounts.installation')),
                ('user', models.ForeignKey(help_text='The user who will receive this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
