# Generated by Django 5.2.3 on 2025-08-05 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_installerprofile_operational_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installerprofile',
            old_name='has_coi_history',
            new_name='coi_history',
        ),
        migrations.RemoveField(
            model_name='installerprofile',
            name='contractor_license_class',
        ),
        migrations.AddField(
            model_name='installerprofile',
            name='license_class',
            field=models.CharField(blank=True, choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='installerprofile',
            name='cidb_category',
            field=models.CharField(blank=True, choices=[('CIVIL', 'Civil'), ('BUILDING', 'Building')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='installerprofile',
            name='cidb_grade',
            field=models.CharField(blank=True, choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3'), ('G4', 'G4'), ('G5', 'G5'), ('G6', 'G6'), ('G7', 'G7')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='installerprofile',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='installerprofile',
            name='company_ssm_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='installerprofile',
            name='operational_state',
            field=models.CharField(blank=True, choices=[('Central 1', 'Central 1'), ('Central 2', 'Central 2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='installerprofile',
            name='pic_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='installerprofile',
            name='pic_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='installerprofile',
            name='pic_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='installerprofile',
            name='pic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='installerprofile',
            name='sst_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='installerprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
