# Generated by Django 5.2.3 on 2025-08-06 08:57

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_has_coi_history_installerprofile_coi_history_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installerprofile',
            old_name='has_insurance',
            new_name='plwc_has_insurance',
        ),
        migrations.AddField(
            model_name='installerprofile',
            name='cidb_certificate',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.upload_to_cert),
        ),
        migrations.AddField(
            model_name='installerprofile',
            name='coi_certificate',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.upload_to_cert),
        ),
        migrations.AddField(
            model_name='installerprofile',
            name='insurance_certificate',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.upload_to_cert),
        ),
        migrations.AddField(
            model_name='installerprofile',
            name='sst_certificate',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.upload_to_cert),
        ),
        migrations.AddField(
            model_name='installerprofile',
            name='st_certificate',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.upload_to_cert),
        ),
    ]
