# Generated by Django 5.2.3 on 2025-08-07 03:17

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_has_insurance_installerprofile_plwc_has_insurance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installerprofile',
            name='operational_state',
        ),
        migrations.AddField(
            model_name='installerprofile',
            name='operational_states',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Central 1', 'Central 1 (Wilayah Persekutuan Kuala Lumpur, Putrajaya)'), ('Central 2', 'Central 2 (Selangor)'), ('Northern', 'Northern (Perak, Kedah, Perlis, Pulau Pinang)'), ('Southern', 'Southern (N.Sembilan, Melaka, Johor)'), ('East Coast', 'East Coast (Pahang, Terengganu, Kelantan)'), ("East M'sia", "East M'sia (Sabah, Sarawak)")], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='installerprofile',
            name='cidb_category',
            field=models.CharField(blank=True, choices=[('B', 'B (Building)'), ('CE', 'CE (Civil Engineering)'), ('ME', 'ME (Mechanical & Electrical)')], max_length=100, null=True),
        ),
    ]
