# Generated by Django 5.2.3 on 2025-08-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_installerprofile_operational_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='installerprofile',
            name='operational_states',
        ),
        migrations.AddField(
            model_name='installerprofile',
            name='operational_states',
            field=models.ManyToManyField(blank=True, to='accounts.state'),
        ),
    ]
