# Generated by Django 5.2.5 on 2025-08-26 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_task',
            field=models.ForeignKey(blank=True, help_text='An optional link to the relevant task, allowing clicks to navigate directly to the task details.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='accounts.task'),
        ),
    ]
