# Generated by Django 5.2.3 on 2025-08-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_chargermodel_customer_installation_servicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='house_type',
            field=models.CharField(choices=[('L', 'Landed House'), ('H', 'High-Rise')], default='landed', max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('JH', 'Johor'), ('KD', 'Kedah'), ('KT', 'Kelantan'), ('ML', 'Melaka'), ('NS', 'Negeri Sembilan'), ('PH', 'Pahang'), ('PK', 'Perak'), ('PL', 'Perlis'), ('PN', 'Penang'), ('SB', 'Sabah'), ('SW', 'Sarawak'), ('SL', 'Selangor'), ('TR', 'Terengganu'), ('KL', 'Kuala Lumpur'), ('LB', 'Labuan'), ('PJ', 'Putrajaya')], max_length=2),
        ),
    ]
