# Generated by Django 5.2.3 on 2025-08-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_house_type_alter_customer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='house_type',
            field=models.CharField(choices=[('L', 'Landed House'), ('H', 'High-Rise')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, choices=[('', 'Choose State'), ('Johor', 'Johor'), ('Kedah', 'Kedah'), ('Kelantan', 'Kelantan'), ('Melaka', 'Melaka'), ('Negeri Sembilan', 'Negeri Sembilan'), ('Pahang', 'Pahang'), ('Penang', 'Penang'), ('Perak', 'Perak'), ('Perlis', 'Perlis'), ('Sabah', 'Sabah'), ('Sarawak', 'Sarawak'), ('Selangor', 'Selangor'), ('Terengganu', 'Terengganu'), ('Kuala Lumpur', 'Kuala Lumpur'), ('Labuan', 'Labuan'), ('Putrajaya', 'Putrajaya')], max_length=20),
        ),
    ]
