# Generated by Django 5.2.3 on 2025-08-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customer_house_type_alter_customer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='installation_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
