# Generated by Django 5.2.3 on 2025-08-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_installation_installation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='chargermodel',
            name='connector_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='chargermodel',
            name='model_name',
            field=models.CharField(choices=[('ABB Terra AC 22', 'ABB Terra AC 22'), ('ABB Terra DC 50', 'ABB Terra DC 50'), ('Delta DC Wallbox 25', 'Delta DC Wallbox 25'), ('Schneider EVlink AC 22', 'Schneider EVlink AC 22'), ('Siemens VersiCharge 22', 'Siemens VersiCharge 22'), ('Tesla Wall Connector Gen 3', 'Tesla Wall Connector Gen 3')], help_text='Select the charger model', max_length=100),
        ),
    ]
