# Generated by Django 5.2.3 on 2025-08-09 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_installation_assigned_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installation',
            old_name='actual_completion_date',
            new_name='installation_created_date',
        ),
        migrations.RemoveField(
            model_name='installation',
            name='installation_date',
        ),
    ]
